[package]
name = "mm_cairo"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria" }

[dev-dependencies]
cairo_test = "2.9.2"

[cairo]
enable-gas = false
sierra-replace-ids = true
